CSCfi/research-fi-frontend

Jenkinsfile

Cscttv 521

---

Jenkinsfile
src/environments/environment.prod.ts

Add build info into the environment.prod.ts file during Jenkins build.

Add build info in Jenkins

---

src/app/ui/header/header.component.html
src/app/ui/header/header.component.scss
src/app/ui/header/header.component.ts

Updated header to fit better on mobile screens

Cscttv 563

---

src/app/ui/footer/footer.component.html
src/app/ui/footer/footer.component.scss
src/app/ui/footer/footer.component.ts
src/environments/environment.prod.ts
src/environments/environment.ts

Show build info in application's footer.
Build info consists of date, time and Git commit hash.

Show build info in footer

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/component/breadcrumbs/breadcrumbs.component.html
src/app/component/breadcrumbs/breadcrumbs.component.ts
src/app/component/home-page/home-page.component.ts
src/app/component/results/results.component.html
src/app/component/results/results.component.ts
src/app/component/search-bar/search-bar.component.ts
src/app/services/search.service.ts

Used local storage to store page number.

Cscttv 585

---

Dockerfile.prod
nginx/default.conf

Changed production build to use non-root version of Nginx container.
Modified Nginx configuration so that all URLs are passed to Angular application.

Use non-root version of Nginx Docker image. Modified Nginx config.

---

src/app/ui/header/header.component.html
src/app/ui/header/header.component.scss
src/app/ui/header/header.component.ts

IE/Edge compatibility and desktop navbar design

Cscttv 581

---

src/app/component/breadcrumbs/breadcrumbs.component.html
src/app/component/home-page/home-page.component.html
src/app/component/home-page/home-page.component.scss
src/app/component/results/results.component.html
src/app/component/results/results.component.scss
src/app/component/search-bar/search-bar.component.html
src/app/ui/footer/footer.component.scss
src/app/ui/header/header.component.scss
src/app/ui/layout/layout.component.html
src/styles-custom.scss
src/styles.scss

Set content max-width to 1440px while enabling background for full width

---

src/app/app.module.ts
src/app/component/home-page/home-page.component.ts
src/app/component/results/results.component.html
src/app/component/results/results.component.ts
src/app/component/search-bar/search-bar.component.html
src/app/component/single/single.component.html
src/app/component/single/single.component.ts

Added <title> tag functionality

---

src/app/component/home-page/home-page.component.html
src/app/component/home-page/home-page.component.ts
src/app/services/search.service.ts

Changed API call to POST method since we need request payload

---

src/app/app.module.ts
src/app/component/results/publications/publications.component.html
src/app/component/results/publications/publications.component.scss
src/app/component/results/publications/publications.component.ts
src/app/component/results/results.component.html
src/app/component/results/results.component.ts
src/app/component/results/sort/sort.component.html
src/app/component/results/sort/sort.component.scss
src/app/component/results/sort/sort.component.ts
src/app/component/search-bar/search-bar.component.ts
src/app/services/search.service.ts

Sort publications by year. Defaults to newest.

Cscttv 522

---

src/app/app.module.ts
src/app/component/filter-sidebar/filter-sidebar.component.html
src/app/component/filter-sidebar/filter-sidebar.component.scss
src/app/component/filter-sidebar/filter-sidebar.component.ts
src/app/component/results/publications/publications.component.ts
src/app/component/results/results.component.html
src/app/services/filter.service.ts
src/app/services/search.service.ts

CSCTTV-522

---

Dockerfile.prod
openshift/Dockerfile
openshift/Jenkinsfile
openshift/template.yml

Added application template and Jenkins pipeline for Rahti container cloud.

Cscttv 638 2

---

src/app/component/results/active-filters/active-filters.component.html
src/app/component/results/active-filters/active-filters.component.scss
src/app/component/results/active-filters/active-filters.component.ts
src/app/component/results/filters/filter-fundings/filter-fundings.component.html
src/app/component/results/filters/filter-fundings/filter-fundings.component.ts
src/app/component/results/filters/filter-publications/filter-publications.component.ts
src/app/component/results/fundings/fundings.component.html
src/app/component/results/fundings/fundings.component.ts
src/app/component/results/pagination/pagination.component.ts
src/app/component/results/publications/publications.component.ts
src/app/component/results/results.component.ts
src/app/component/results/sort/sort.component.ts
src/app/component/search-bar/search-bar.component.ts
src/app/component/single-funding/single-funding.component.ts
src/app/services/filter.service.ts
src/app/services/search.service.ts
src/app/services/single-item.service.ts

Changed filtering into more dynamic style. Still under work.

CSCTTV-666

---

Jenkinsfile
src/environments/environment.prod.ts
src/environments/environment.ts

Removed hard coded 'http://' from environment file property 'apiUrl'.

Cscttv 643

---

openshift/template.yml

How many old builds are kept in Rahti

Build history limit

---

nginx/default.conf

Enable gzip compression in Nginx

Enable gzip compression in Nginx

---

src/app/component/result-tab/result-tab.component.ts
src/app/component/results/filters/filter-fundings/filter-fundings.component.ts
src/app/component/results/filters/filter-organizations/filter-organizations.component.ts
src/app/component/results/filters/filter-persons/filter-persons.component.ts
src/app/component/results/search-results/search-results.component.ts
src/app/component/results/sort/sort.component.ts
src/app/component/search-bar/search-bar.component.ts
src/app/component/single-funding/single-funding.component.ts
src/app/component/single-organization/single-organization.component.ts
src/app/component/single-publication/single-publication.component.ts
src/app/ui/header/header.component.ts

Changed service imports to use relative path

Changed service imports to use relative path

---

src/app/app.component.ts
src/app/app.module.ts
src/app/services/app-config-service.service.ts
src/polyfills.ts

Fix run time JS error caused by Application Performance Monitoring

Fix run time JS error caused by Application Performance Monitoring

---

server.ts

Removed line, which prevents caching of the application.

Enabled caching

---

openshift/Jenkinsfile-devel
openshift/Jenkinsfile-production
openshift/Jenkinsfile-test
openshift/template-devel.yml
openshift/template-production.yml
openshift/template-test.yml

Separate OpenShift templates for devel, test and production environments

Separate OpenShift templates for devel, test and production environments

---

openshift/template-production.yml

Changed source git branch from master to production. Increased build history limit.

Changed source git branch from master to production.

---

nginx_reverse_proxy/angular/devel-productiondata/Dockerfile
nginx_reverse_proxy/angular/devel-productiondata/nginx.conf
nginx_reverse_proxy/angular/devel-productiondata/nginx_angular.yml

Separate reverse proxy config for devel productiondata

Separate reverse proxy config for devel productiondata

---

nginx_reverse_proxy/api/devel/nginx.conf
nginx_reverse_proxy/api/production/nginx.conf

Add CORS headers in nginx reverse proxy

Add CORS headers in nginx reverse proxy

---

nginx_reverse_proxy/api/devel/nginx.conf
nginx_reverse_proxy/api/devel/nginx_api_devel.yml
nginx_reverse_proxy/api/production/nginx.conf

Cors modifications in nginx

---

nginx_reverse_proxy/api/production/nginx_api_production.yml

Fixed bug in production api revproxy OpenShift template

Fixed bug in production api revproxy OpenShift template

---

nginx_reverse_proxy/api/devel/nginx.conf
nginx_reverse_proxy/api/production/nginx.conf
src/app/app.component.ts

Fixed bug in handling of APM messages in Nginx reverse proxy

Fixed bug in handling of APM messages in Nginx reverse proxy

---

nginx_reverse_proxy/angular/devel-productiondata/nginx.conf
nginx_reverse_proxy/angular/devel/nginx.conf
nginx_reverse_proxy/angular/production/nginx.conf

Nginx reverse proxy config for feedback route.

Nginx reverse proxy config for feedback route.

---

src/app/services/email.service.ts

Modified email sending configuration

Modified email sending configuration

---

nginx_reverse_proxy/angular/devel-productiondata/nginx.conf
nginx_reverse_proxy/angular/devel/nginx.conf
nginx_reverse_proxy/angular/production/nginx.conf

Nginx rate limit for /feedback route

Nginx rate limit for /feedback route

---

nginx_reverse_proxy/angular/production/nginx.conf

Modified nginx config for frontend reverse proxy in production.

Modified nginx config for frontend reverse proxy in production.

---

nginx_reverse_proxy/angular/production/nginx.conf

Modified domain names in production nginx.conf

Modified domain names in production nginx.conf

---

nginx_reverse_proxy/angular/production/nginx.conf

Temporarily direct traffic to development version.

Temporarily direct traffic to development version.

---

nginx_reverse_proxy/angular/devel-productiondata/nginx.conf
nginx_reverse_proxy/angular/devel/nginx.conf
nginx_reverse_proxy/angular/production/nginx.conf
nginx_reverse_proxy/api/devel/nginx.conf
nginx_reverse_proxy/api/production/nginx.conf

Added Rahti health check endpoints to Nginx

Added Rahti health check endpoints to Nginx

---

nginx_reverse_proxy/angular/production/nginx.conf
src/app/ui/header/header.component.html

Activated language select. Updated language version links. Temporarily serve also swe version from finnish domain.

Activated language select. Updated language version links.

---

src/app/component/results/organizations/organizations.component.scss
src/app/component/search-bar/search-bar.component.html
src/app/component/search-bar/search-bar.component.ts
src/app/ui/header/header.component.html
src/i18n/messages.en.xlf
src/i18n/messages.sv.xlf

Added some missing translations

Translation fix

---

openshift/Jenkinsfile-production
openshift/Jenkinsfile-qa
openshift/template-qa.yml

OpenShift template and Jenkins pipeline for application researchfi-frontend-qa. Removed wait step from production Jenkins pipeline.

OpenShift template and Jenkins pipeline for QA Angular app

---

package-lock.json
package.json
src/app/app.component.ts
src/app/services/error-handler.service.ts

Send Javascript errors to APM server

Send Javascript errors to APM server

---

src/app/universal-interceptor.ts

Prevent mail configuration in config.json from leaking into page source

Prevent mail configuration in config.json from leaking into page source

---

src/app/component/search-bar/search-bar.component.html
src/app/models/news.model.ts

Hotfix v1.5.1

---

openshift/Dockerfile

Modified Docker source image registry

Use Rahti internal Docker registry when building devel.

---

.gitignore
src/app/common-components/divider/divider.component.html
src/app/component/home-page/home-page.component.html
src/app/component/science-politics/external-links/external-links.component.html
src/app/component/science-politics/external-links/external-links.component.ts
src/i18n/messages.en.xlf
src/i18n/messages.sv.xlf

Removed i18n tag from divider.

Translations for 'Science and research elsewhere' section. 

---

src/app/component/results/filters/filters.component.ts
src/app/component/results/results.component.ts
src/app/component/science-politics/figures/single-figure/single-figure.component.html
src/app/component/single/share/share.component.ts
src/app/component/single/single-dataset/single-dataset.component.html
src/app/component/single/single-funding/single-funding.component.html
src/app/component/single/single-infrastructure/single-infrastructure.component.html
src/app/component/single/single-organization/single-organization.component.html
src/app/component/single/single-publication/single-publication.component.html
src/app/component/single/single-publication/single-publication.component.ts
src/app/services/filters/funding-filter.service.ts

CSCTTV-1857
CSCTTV-1856
CSCTTV-1855

Cscttv 1856

---

openshift/template-deployment-config-devel-branch-production-api.yml
openshift/template-devel.yml
openshift/template-production.yml
openshift/template-qa.yml
openshift/template-releasetest.yml
src/app/shared/services/app-config-service.service.ts

Add auth_config.json in OpenShift deployment. Remove obsolete code from appConfigService.

Add auth_config.json in OpenShift deployment. Remove obsolete code from appConfigService.

---

openshift/template-deployment-config-devel-branch-production-api.yml
openshift/template-devel.yml
openshift/template-production.yml
openshift/template-qa.yml
openshift/template-releasetest.yml

Modify OpenShift config map key names to enable language specific auth_config.json.

Modify OpenShift config map key names.

---

openshift/template-production.yml

Add auth config files in frontend-production-staging container.

Add auth config files in frontend-production-staging container.

---

src/index.html

Change matomo site id to 1 (production)

Change matomo site id to 1

---

openshift/Jenkinsfile-devel

Add Jenkins pipeline stage to push image to Artifactory.

Add Jenkins pipeline stage to push image to Artifactory.

---

openshift/Jenkinsfile-devel

Remove Jenkins pipeline stage which uses "oc tag".

Remove Jenkins pipeline stage.

---

nginx_reverse_proxy/angular/artifactory/buildconfig_nginx_revproxy_angular_production.yml
nginx_reverse_proxy/api/artifactory/buildconfig_nginx_revproxy_api_production.yml
openshift/artifactory/buildconfig_frontend_production.yml

Add OpenShift build configs for Artifactory builds.
- production Angular frontend
- production Nginx reverse proxy for Angular frontend
- production Nginx reverse proxy for API

Add OpenShift build configs for Artifactory builds.

---

src/app/layout/header/header.component.html
src/app/layout/header/header.component.ts
src/app/mydata/components/profile/profile-summary/profile-summary.component.html
src/app/mydata/components/profile/profile-summary/summary-publications/summary-publications.component.html
src/app/mydata/components/profile/profile-summary/summary-publications/summary-publications.component.ts
src/app/mydata/components/profile/profile.component.html
src/app/mydata/components/profile/profile.component.ts
src/app/shared/components/dialog/dialog-template/dialog-template.component.html
src/app/shared/components/dialog/dialog-template/dialog-template.component.ts
src/i18n/messages.en.xlf

Logout dialog
Unbind dialog actions from original data
Discard dialog
Summary panel divider logic

Draft layout changes

---

src/app/layout/header/header.component.ts
src/app/mydata/components/profile/profile-panel/profile-panel.component.ts
src/app/mydata/components/welcome-stepper/stepper-navigation/stepper-navigation.component.ts
src/app/mydata/services/patch.service.ts
src/app/shared/services/app-settings.service.ts

Alert user if draft data in session storage
Handle deselection of confirmed items

Alert for unsaved data & deselection of items

---

src/app/layout/header/header.component.html
src/app/layout/header/header.component.scss
src/app/layout/header/header.component.ts
src/app/mydata/components/profile/profile-panel/profile-panel.component.html
src/app/mydata/components/profile/profile-panel/profile-panel.component.ts
src/app/mydata/pipes/handle-fetched-publications.pipe.ts

Fix for added publication render when no publications from ORCID
Fix for long mobile menu not fitting when dropdown expanded
Render mobile menu on under 1200px breakpoint

Fix for mobile nav & mydata publication add

---

src/app/mydata/components/profile/draft-summary/draft-summary.component.ts
src/app/mydata/components/profile/editor-modal/editor-modal.component.ts
src/app/mydata/components/profile/profile-panel/panel-array-item/panel-array-item.component.html
src/app/mydata/components/profile/profile-panel/panel-array-item/panel-array-item.component.ts
src/app/mydata/components/profile/profile-panel/profile-panel.component.html
src/app/mydata/components/profile/profile-panel/profile-panel.component.ts
src/app/mydata/components/profile/profile-panel/search-portal/search-portal-results/search-portal-results.component.ts
src/app/mydata/components/profile/profile-panel/search-portal/search-portal.component.html
src/app/mydata/components/profile/profile-panel/search-portal/search-portal.component.ts
src/app/mydata/components/profile/profile-summary/profile-summary.component.ts
src/app/mydata/components/profile/profile-summary/summary-datasets/summary-datasets.component.html
src/app/mydata/components/profile/profile-summary/summary-datasets/summary-datasets.component.ts
src/app/mydata/components/profile/profile.component.html
src/app/mydata/components/profile/profile.component.ts
src/app/mydata/constants/index.ts
src/app/mydata/models/dataset.model.ts
src/app/mydata/models/item/dataset-item.model.ts
src/app/mydata/models/item/publication-item.model.ts
src/app/mydata/models/publication.model.ts
src/app/mydata/services/datasets.service.ts
src/app/mydata/services/draft.service.ts
src/app/mydata/services/search-portal.service.ts

Leverage query settings from portal
Fix for removing publications
Render added datasets in summary
Datasets draft logic
Handle datasets from profile API
Dynamic item delete method
Simple models for publication and dataset items
Handle preselection of search results
Fix remove button for datasets

Improvements to dynamic portal search

---

nginx_reverse_proxy/angular/mydata-demo/Dockerfile
nginx_reverse_proxy/angular/mydata-demo/nginx.conf
nginx_reverse_proxy/angular/mydata-demo/nginx_angular.yml

Add nginx revproxy for mydata demo Angular application.

Add nginx revproxy for mydata demo Angular application.

---

src/app/layout/error-modal/error-modal.component.html
src/app/layout/error-modal/error-modal.component.ts
src/app/layout/footer/footer.component.html
src/app/layout/footer/footer.component.ts
src/app/portal/services/static-data.service.ts
src/app/shared/components/dialog/dialog-template/dialog-template.component.html
src/app/shared/components/dialog/dialog.component.ts
src/app/shared/constants.ts
src/app/shared/services/intercept.service.ts
src/i18n/messages.en.xlf
src/i18n/messages.sv.xlf

CMS connection error handling
Added comment
Introduced shared constants
Translated CMS error content
Use shared dialog component with error handler

Enable use of portal if CMS service is down

---

src/app/mydata/components/home/home.component.html
src/app/mydata/components/profile/profile-summary/summary-affiliations/summary-affiliation.component.ts
src/app/mydata/components/profile/profile.component.html
src/app/mydata/components/profile/search-portal/custom-paginator-intl/custom-paginator-intl.component.ts
src/app/mydata/components/profile/search-portal/search-portal.component.ts
src/app/mydata/components/welcome-stepper/stepper-navigation/stepper-navigation.component.html
src/app/mydata/components/welcome-stepper/stepper-navigation/stepper-navigation.component.ts
src/app/mydata/components/welcome-stepper/welcome-stepper.component.html
src/app/mydata/components/welcome-stepper/welcome-stepper.component.ts
src/i18n/messages.en.xlf
src/i18n/messages.sv.xlf

Enable step decrement on third step
Home view layout changes
Layout change to second step
Data fetch and profile delete dialog fine tunings
Added missing translations

MyData demo fine tunings

---

src/app/layout/header/header.component.html
src/app/mydata/components/profile/cards/contact-card/contact-card.component.ts
src/app/mydata/components/profile/profile-summary/profile-summary.component.ts
src/app/mydata/components/profile/profile.component.ts
src/app/mydata/services/patch.service.ts
src/i18n/messages.en.xlf

Added missing translations
Prevent empty payload API requests

MyData API request optimization and translations

---

src/app/layout/footer/footer.component.ts
src/app/mydata/components/profile/profile-panel/activity-item/activity-item.component.html
src/app/mydata/components/profile/profile-panel/activity-item/activity-item.component.ts
src/app/mydata/components/profile/profile-panel/panel-array-item/panel-array-item.component.html
src/app/mydata/components/profile/profile-panel/panel-array-item/panel-array-item.component.ts
src/app/mydata/components/profile/profile-panel/profile-panel.component.html
src/app/mydata/components/profile/profile-panel/profile-panel.component.ts
src/app/mydata/components/profile/profile-summary/summary-portal-items/summary-portal-items.component.html
src/app/mydata/components/profile/profile-summary/summary-portal-items/summary-portal-items.component.ts
src/app/mydata/components/welcome-stepper/welcome-stepper.component.ts
src/app/mydata/utils.ts

Enabled merging of publications that share DOI
Link to mydata review form
Expand all expansion panels that have under 7 items
Enable route refresh / locale change on stepper

MyData demo fine tunings #3

---

src/app/portal/components/funding-calls/single-funding-call/single-funding-call.component.ts
src/app/portal/components/single/single-organization/single-organization.component.ts
src/app/shared/services/error-handler.service.ts
src/app/shared/services/window.service.ts

Browser check for DOMParser
Log browser info into APM

SSR Fixes #2

---

.github/dependabot.yml
.github/workflows/codeql-analysis.yml
package-lock.json
package.json
server.ts
src/app/layout/footer/footer.component.html
src/app/portal/components/news/news-card/news-card.component.html
src/app/portal/components/results/infrastructures/infrastructures.component.html
src/app/portal/components/science-politics/tki-reports/tki-reports.component.html
src/app/portal/components/single/single-dataset/single-dataset.component.html
src/app/portal/components/single/single-infrastructure/single-infrastructure.component.html
src/app/portal/components/single/single-publication/publication-links/publication-links.component.html
src/app/portal/components/single/single-publication/single-publication.component.ts
src/app/portal/pipes/handle-infrastructure-link.pipe.ts
src/app/portal/portal.module.ts

CodeQL & Dependabot workflows for GH Actions

---

src/app/layout/header/header.component.html
src/app/mydata/components/home/home.component.ts
src/app/mydata/components/login/login.component.ts
src/app/mydata/components/profile/profile-summary/profile-summary.component.html
src/app/mydata/components/profile/profile.component.ts
src/app/mydata/components/welcome-stepper/welcome-stepper.component.ts
src/app/portal/components/single/single-publication/single-publication.component.ts
src/app/shared/services/app-settings.service.ts
src/app/shared/services/utility.service.ts
src/styles-custom.scss

Combination of next issues:
CSCTTV-2177
CSCTTV-2195
CSCTTV-2225

MyData title and group labels & app lang indicator

---

src/app/mydata/components/home/home.component.html
src/app/mydata/components/login/login.component.html
src/app/mydata/components/welcome-stepper/welcome-stepper.component.html
src/app/portal/components/funding-calls/funding-call-preview/funding-call-preview.component.html
src/app/portal/components/home-page/home-page.component.scss
src/app/portal/components/news/news-card/news-card.component.html
src/app/portal/components/result-tab/result-tab.component.html
src/app/portal/components/result-tab/result-tab.component.scss
src/app/portal/components/results/filters/filters.component.html
src/app/portal/components/results/results.component.scss-shared.scss
src/app/portal/components/science-politics/figures/figures.component.html
src/app/portal/components/science-politics/research-innovation-system/research-innovation-system.component.html
src/app/portal/components/search-bar/search-bar.component.html
src/app/portal/components/search-bar/search-bar.component.scss
src/app/portal/components/search-bar/search-bar.component.scss-theme.scss
src/app/portal/components/search-bar/search-bar.component.ts
src/app/portal/portal.module.ts
src/styles-custom-expansion-panel.scss
src/styles-custom.scss

Keyboard focus indicator adjustments

CSCTTV-2289

---

package-lock.json
package.json

Reverts CSCfi/research-fi-frontend#1208
Needs Angular 13

Revert "Bump @angular/cli from 12.2.13 to 13.2.3"

---

src/app/layout/header/header.component.scss
src/app/layout/review/review.component.scss
src/app/mydata/components/profile/profile-panel/profile-panel.component.html
src/app/mydata/components/profile/profile.component.html
src/app/mydata/components/profile/search-portal/search-portal-results/search-portal-results.component.html
src/app/mydata/components/profile/search-portal/search-portal-results/search-portal-results.component.scss
src/app/mydata/components/profile/search-portal/search-portal-results/search-portal-results.component.ts
src/app/mydata/components/welcome-stepper/welcome-stepper.component.ts
src/app/mydata/mydata-shared.scss
src/app/mydata/services/profile.service.ts
src/app/portal/components/results/filters/filters.component.html
src/styles-custom.scss

Keyboard focus indicator improvements
Add step to site title
Display primary colored outline around certain Material UI elements
Congruent focus indicator area for all navigation links
CSCTTV-2260
CSCTTV-2289
CSCTTV-2177

Accessibility improvements

---

src/app/portal/components/single/single-funding/single-funding.component.html
src/app/portal/components/single/single-funding/single-funding.component.ts
src/app/portal/components/single/single-result.scss-shared.scss
src/app/portal/models/funding/funding.model.ts
src/app/portal/models/funding/recipient.model.ts
src/app/portal/models/utils.ts

Handle EU funding recipients when recipient type is consortium

CSCTTV-2121

---

src/app/layout/header/header.component.html
src/app/layout/header/header.component.scss
src/app/layout/header/header.component.scss-theme.scss
src/app/layout/header/header.component.ts
src/app/portal/components/results/results.component.html
src/app/portal/components/results/sort/sort.component.html
src/app/portal/components/results/sort/sort.component.ts
src/app/portal/components/search-bar/search-bar.component.html
src/app/portal/components/search-bar/search-bar.component.ts
tsconfig.json

- Sort component with Mat-menu module
- Language switcher with Mat-menu module
- Handle dropdown header link with Mat-menu module
- Enable opening of search target menu with enter key
- Removed unused styles
- Changed ESLint from 'es2018' to 'es2019' in tsconfig lib settings

CSCTTV-2444

---

src/app/portal/components/news/news-card/news-card.component.html
src/app/portal/components/single/single-result.scss-shared.scss

Minor adjustments to news card and single result sidebar heading styling.

CSCTTV-2503

---

src/app/layout/header/header.component.html
src/app/layout/header/header.component.scss
src/app/portal/components/results/results.component.html
src/app/portal/components/results/results.component.scss
src/app/portal/components/results/results.component.ts
src/i18n/messages.sv.xlf

[CSCTTV-2615](https://jira.eduuni.fi/browse/CSCTTV-2615)
[CSCTTV-2616](https://jira.eduuni.fi/browse/CSCTTV-2616)
[CSCTTV-2620](https://jira.eduuni.fi/browse/CSCTTV-2620)
[CSCTTV-2621](https://jira.eduuni.fi/browse/CSCTTV-2621)

Multiple small UI fixes

---

service_break_page/Dockerfile
service_break_page/html/index.html
service_break_page/service_break_page.yml

Add Rahti config for service break page.

Add Rahti config for service break page.

---

service_break_page/Dockerfile
service_break_page/default.conf

Add nginx default.conf for service break page Rahti deployment

Add nginx default.conf for service break page Rahti deployment

---

src/app/portal/components/science-politics/figures/figures.component.html
src/app/portal/components/science-politics/figures/figures.component.ts
src/app/portal/directives/scroll-spy.directive.ts

https://jira.eduuni.fi/browse/CSCTTV-2688

Fix for anchor scroll in research figures

---

src/app/portal/components/single/single-funding-call/single-funding-call.component.html
src/app/portal/components/single/single-funding-call/single-funding-call.component.ts
src/app/portal/services/search.service.ts
src/app/portal/services/sort.service.ts
src/i18n/messages.en.xlf
src/i18n/messages.sv.xlf

https://jira.eduuni.fi/browse/CSCTTV-2693

CSCTTV-2693

---

src/app/portal/components/single/single-dataset/single-dataset.component.html

Reverts CSCfi/research-fi-frontend#1362

Revert "Dataset relations column spacing"

---

src/app/portal/components/results/filters/filters.component.ts
src/app/portal/components/results/funding-call-category-filters/funding-call-category-filters.component.ts
src/app/portal/components/results/results.component.html
src/app/portal/portal.module.ts
src/app/portal/services/filters/aggregation.service.ts
src/app/portal/services/filters/funding-call-filter.service.ts
src/app/portal/services/tab-change.service.ts
src/app/shared/components/table/table.component.html

Various fixes to 1.17 production build

CSCTTV-2703

---

.github/workflows/combine-dependabot-prs.yml

https://jira.eduuni.fi/browse/CSCTTV-2791

Workflow for combining Dependabot PRs

---

src/app/portal/models/funding/recipient.model.ts
src/app/portal/services/sort.service.ts

Adjusted funding sorting by funded name logic to sort by receiver last name
https://jira.eduuni.fi/browse/CSCTTV-2190

CSCTTV-2190

---

.github/workflows/combine-dependabot-prs.yml

Minor adjustments to dependabot combined PRs workflow.
- Workflow now works with commit status checks.
- Run status check on default

Dependabot combine workflow modification

---

src/app/mydata/components/home/home.component.html
src/app/mydata/components/profile/profile.component.ts
src/app/mydata/components/service-deployment/cancel-deployment/cancel-deployment.component.html
src/app/mydata/components/service-deployment/cancel-deployment/cancel-deployment.component.ts
src/app/mydata/components/service-deployment/orcid-data-fetch/orcid-data-fetch.component.html
src/app/mydata/components/service-deployment/orcid-data-fetch/orcid-data-fetch.component.ts
src/app/mydata/components/service-deployment/service-deployment.component.html
src/app/mydata/components/service-deployment/service-deployment.component.ts
src/app/mydata/mydata-routing.module.ts
src/app/mydata/services/profile.service.ts

Fix for https://jira.eduuni.fi/browse/CSCTTV-2832 and other fine tunings to service deployment

Service deployment fine tunings

---

src/app/mydata/components/profile/data-sources/data-sources-table/data-sources-table.component.html
src/app/mydata/components/profile/data-sources/data-sources-table/data-sources-table.component.ts
src/app/mydata/components/profile/data-sources/data-sources.component.ts
src/app/mydata/components/profile/profile-panel/panel-array-item/panel-array-item.component.html
src/app/mydata/components/profile/profile.component.html
src/app/mydata/constants/index.ts
src/app/mydata/models/description.model.ts
src/app/mydata/models/personal.model.ts
src/app/mydata/mydata-routing.module.ts
src/app/shared/components/table/table.component.html
src/bootstrap_overrides.scss
src/styles-custom.scss

Related to https://jira.eduuni.fi/browse/CSCTTV-2321 and https://jira.eduuni.fi/browse/CSCTTV-2320

Data sources fine tunings

---

src/app/mydata/components/profile/cards/contact-card/contact-card.component.html
src/app/mydata/components/profile/cards/contact-card/contact-card.component.ts
src/app/mydata/components/profile/cards/profile-editor-card-header/profile-editor-card-header.component.html
src/app/mydata/components/profile/cards/profile-editor-card-header/profile-editor-card-header.component.ts
src/app/mydata/components/profile/data-sources/data-sources-selection-actions/data-sources-selection-actions.component.ts
src/app/mydata/components/profile/data-sources/data-sources-table/data-sources-table.component.html
src/app/mydata/components/profile/data-sources/data-sources-table/data-sources-table.component.scss
src/app/mydata/components/profile/data-sources/data-sources-table/data-sources-table.component.ts
src/app/mydata/components/profile/editor-modal/editor-modal.component.html
src/app/mydata/components/profile/editor-modal/editor-modal.component.ts
src/app/mydata/components/profile/profile-summary/profile-summary.component.html
src/app/mydata/components/profile/profile-summary/profile-summary.component.ts
src/app/mydata/components/profile/profile.component.ts
src/app/mydata/components/profile/search-portal/search-portal.component.html
src/app/mydata/services/snackbar.service.ts
src/app/portal/components/news/news-results/news-results.component.html
src/app/portal/services/settings.service.ts
src/app/shared/components/dialog/dialog-template/dialog-template.component.html
src/app/shared/components/dialog/dialog.component.ts
src/app/shared/components/search/search.component.html
src/app/shared/components/search/search.component.scss
src/app/shared/components/search/search.component.ts
src/app/shared/components/table/table-card/table-card.component.html
src/app/shared/components/table/table-card/table-card.component.ts
src/app/shared/directives/autofocus.directive.ts
src/app/shared/shared.module.ts
src/styles-custom-palettes.scss
src/styles-custom.scss

- Minor changes to MyData datasources and search input component
- Accessibility improvements to dialog

CSCTTV-2494 - Dialog accessibility - datasources - search

---

src/app/mydata/components/profile/profile-summary/profile-summary.component.html
src/app/mydata/components/profile/profile-summary/profile-summary.component.ts
src/app/shared/components/buttons/primary-action-button/primary-action-button.component.html
src/app/shared/components/buttons/primary-action-button/primary-action-button.component.ts
src/app/shared/components/buttons/secondary-button/secondary-button.component.html
src/app/shared/components/buttons/secondary-button/secondary-button.component.ts

Continuation to CSCTTV-2494, search from portal dialog accessibility

Announce 'select' button with description when using screen reader

---

src/app/mydata/components/profile/editor-modal/editor-modal.component.html
src/app/mydata/components/profile/editor-modal/editor-modal.component.ts
src/app/mydata/components/profile/profile-panel/profile-panel.component.html
src/app/mydata/components/profile/profile-panel/profile-panel.component.ts
src/app/mydata/components/profile/profile-summary/profile-summary.component.ts
src/app/mydata/components/profile/profile.component.ts
src/app/mydata/components/profile/search-portal/search-portal-results/search-portal-results.component.ts
src/app/mydata/components/profile/search-portal/search-portal.component.html
src/app/mydata/components/profile/search-portal/search-portal.component.ts
src/app/mydata/services/collaborations.service.ts
src/app/portal/components/privacy/privacy.component.html
src/app/portal/components/single/single-organization/single-organization.component.html
src/app/shared/components/dialog/dialog-template/dialog-template.component.html
src/app/shared/components/dialog/dialog-template/dialog-template.component.ts
src/app/shared/components/dialog/dialog.component.ts
src/styles-custom.scss
src/types/index.ts

https://jira.eduuni.fi/browse/CSCTTV-2626
- Select all -checkbox position
- Initial approach for tab base dialog content (search from portal)
- Transformed cooperation choices api endpoint to lowercase

Updates to editor modal

---

src/i18n/messages.en.xlf
src/i18n/messages.sv.xlf

Fix for translation string bug

---

src/app/layout/footer/footer.component.html
src/app/layout/footer/footer.component.ts
src/app/mydata/components/home/home.component.html
src/app/mydata/components/home/home.component.ts
src/app/mydata/components/welcome-stepper/welcome-stepper.component.html
src/app/mydata/components/welcome-stepper/welcome-stepper.component.ts
src/app/mydata/mydata.module.ts
src/app/shared/services/dialog-events.service.ts
src/app/shared/shared.module.ts
src/i18n/messages.en.xlf
src/i18n/messages.sv.xlf
src/i18n/messages.xlf

Move welcome stepper to footer so that it can be used outside of home component.
Create a modal event service that manages the on and off state for quickstart guide dialog. 
Components that are at the end of component tree can use the service for managing the quickstart guide dialog.

CSCTTV-2975

---

src/app/mydata/components/service-deployment/orcid-data-fetch/orcid-data-fetch.component.ts
src/app/mydata/services/auth-guard.service.ts

CSCTTV-3147 Modified AuthGuard.canActivate and OrcidDataFetchComponent,
Modified Observable handling in AuthGuard.canActivate. Added comments to describe canActivate logic.
Modified checking of API response status in OrcidDataFetchComponent.

CSCTTV-3147 Modified AuthGuard.canActivate and OrcidDataFetchComponent

---

src/app/mydata/services/collaborations.service.ts
src/app/mydata/services/datasets.service.ts
src/app/mydata/services/fundings.service.ts
src/app/mydata/services/publications.service.ts

Modify access token handling in publication, funding, dataset and collaboration API requests

Modify how access token is set in HTTP header in some of the API requests
